# TensorFlow Linear Algebra Examples

These are some notes about TensorFlow. These notes are a modified version from the note of a course in Deep Neural Networks at Washington University in St. Louis.

I added clarifications and some extra examples to this code. I also added explanations and used different concepts to test and exemplify the use of TensorFlow and Keras.

In [16]:
import tensorflow as tf

matrix1 = tf.constant([[3., 3.]]) 
matrix2 = tf.constant([[2.],[2.]])

# To clarify this. In matrix1 we are creating a tensor with constant entries.
# In this particular case, we create a shape = (1,2) tensor, that is, a 
# 1x2 matrix or a vector of dimension 2.
#
# For matrix2 we create a shape = (2,1) tensor, that is, a 2x1 matrix which is a 
# column vector.
#
# Just to exemplify a shape = (3,2,2) tensor is like a cube with 3, 
# 2x2 matrices inside.
# 

A = tf.constant(10.0, shape = (3,2,2))

print(A) # three layers with 2x2 constant matrices at each one.

# The first coordinate of shape give us the number of layers.

A[1][0,:] # we access matrix 1 and then we access row 0.



tf.Tensor(
[[[10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]]

 [[10. 10.]
  [10. 10.]]], shape=(3, 2, 2), dtype=float32)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10., 10.], dtype=float32)>

## Multiplications

In [17]:
# Multiplication of two vectors using TensorFlow

product = tf.matmul(matrix1, matrix2) # Here we multiply two vectors - classic multiplication
product

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

In [20]:
tf.matmul(matrix1,A) # Here we multiply a vector by a tensor

# We get the multiplication of this vector
# with each matrix inside the tensor.

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[60., 60.]],

       [[60., 60.]],

       [[60., 60.]]], dtype=float32)>

## Substract a constant from a variable

In [21]:
# Important information about TensorFlow variables and constant variables.

x = tf.Variable([1.0, 1.0]) # creating tensors in this case with shape (0,2,1)
                            # This is a vector.
    
a = tf.constant([3.0, 3.0])

sub = tf.subtract(x, a) 
print(sub)
print(sub.numpy())

# I think that variables can be modified but the other 'Python' var we are 
# definning here cannot be modified (for instance variable a).
#
# There is a subtle but important difference between Python and TensorFlow
# variables.  TensorFlow variables can be modified as written above.

# To modify one of these variables we use the command assign
# or any OP command

x.assign([4.0,6.0])

tf.Tensor([-2. -2.], shape=(2,), dtype=float32)
[-2. -2.]


<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([4., 6.], dtype=float32)>

In [22]:
# substraction with this new value

sub = tf.subtract(x,a)
print(sub)
print(sub.numpy())



tf.Tensor([1. 3.], shape=(2,), dtype=float32)
[1. 3.]


# Introduction to Keras - Neural Networks

Keras is part of TensorFlow. It is useful to create neural networks. 
We will use a particular data set from Heaton's website. This dataset 
is called MPG.

<!-- - Predictors/Inputs
    - Fill any missing inputs with the median for that column. Use missing_median.
    - Encode textual/categorical values with encode_text_dummy.
    - Encode numeric values with encode_numeric_zscore.
- Output
    - Discard rows with missing outputs.
    - Encode textual/categorical values with encode_text_index.
    - Do not encode output numeric values.
- Produce final feature vectors (x) and expected output (y) with to_xy.-->

In [23]:
## Simple TensorFlow Regression: MPG dataset.

## This data set has some particularities. The input is numerical and 
## categorial, some of the values are missing values.

# Libraries

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics


# loading the dataset

df = pd.read_csv("https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", na_values=['NA', '?'])
cars = df['name']

# filling missing values

df['horsepower'] = df['horsepower'].fillna(df.horsepower.median())

# Turning this dataframe into a matrix

x = df[['cylinders','displacement','horsepower','weight','acceleration','year','origin']].values

y = df.mpg.values # we want to predict mpg values from the matrix X. --> this is the important idea.

# We want to do regression, x is the predictor variables and y 
# is the dependent variable.

# Building the neural network

model = Sequential()
model.add(Dense(25, input_dim = x.shape[1], activation = 'relu')) # Hidden 1 - Input, because the input is fixed.
model.add(Dense(10, activation='relu')) # Hidden 2
model.add(Dense(1)) # Output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

# Entry - layer 0
# We add 25 neurons hidden 1 - layer 1
# We add 10 neurons hidden 2 - layer 2
# We add 1 neuron Output - layer 3

# These are four layers - entry, hidden 1, hidden 2, output.

# epoch takes data for evaluating the trainning/fitting.
#
# From the documentation
#
# Epoch: an arbitrary cutoff, generally defined as "one pass over the entire dataset", 
# used to separate training into distinct phases, which is useful for logging and periodic evaluation.



Epoch 1/100
13/13 - 0s - loss: 22641.8574
Epoch 2/100
13/13 - 0s - loss: 2086.2178
Epoch 3/100
13/13 - 0s - loss: 652.9379
Epoch 4/100
13/13 - 0s - loss: 356.7738
Epoch 5/100
13/13 - 0s - loss: 130.9985
Epoch 6/100
13/13 - 0s - loss: 107.8818
Epoch 7/100
13/13 - 0s - loss: 107.5123
Epoch 8/100
13/13 - 0s - loss: 103.6338
Epoch 9/100
13/13 - 0s - loss: 104.3011
Epoch 10/100
13/13 - 0s - loss: 100.6987
Epoch 11/100
13/13 - 0s - loss: 101.7947
Epoch 12/100
13/13 - 0s - loss: 99.4912
Epoch 13/100
13/13 - 0s - loss: 99.5629
Epoch 14/100
13/13 - 0s - loss: 99.4179
Epoch 15/100
13/13 - 0s - loss: 100.3084
Epoch 16/100
13/13 - 0s - loss: 99.4295
Epoch 17/100
13/13 - 0s - loss: 99.3718
Epoch 18/100
13/13 - 0s - loss: 98.4875
Epoch 19/100
13/13 - 0s - loss: 98.6881
Epoch 20/100
13/13 - 0s - loss: 99.2183
Epoch 21/100
13/13 - 0s - loss: 97.5970
Epoch 22/100
13/13 - 0s - loss: 97.0287
Epoch 23/100
13/13 - 0s - loss: 97.9476
Epoch 24/100
13/13 - 0s - loss: 95.9145
Epoch 25/100
13/13 - 0s - loss: 95

## Introduction to Neural Network Hyperparameters.

Some ideas about our previous code:

1. The network need one input neuron for each column in the dataset (including empty variables etc).
2. How do we choose the number of hidden layers and the number of neuros on each layer?
   This question has not already a clear answer. These are hyperparameters. This parameters
   can affect neural network performance. There are not clearly defined means of setting them.
3. More hidden neurons -> more capability to fit complex problems. 
   Too many neurons --> risk overfitting.
   Too few --> risk underfitting
4. How many layers you have is algo a hyperparameter. 
   More neurons -> neural network perform more of its feature engineering and data preprocessing
   Risk of this -> expense of tranining times, risk of overfitting.
5. In general networks will have a triangle shape, where we have a lot of neurons on the input side 
   and one, or a small amount of outputs and the output side.
   
__Controlling the Amount of Output__

The program produces one line of output for each training epoch. You can eliminate this output by setting the verbose setting of the fit command:

- verbose=0 - No progress output (use with Jupyter if you do not want output)
- verbose=1 - Display progress bar, does not work well with Jupyter
- verbose=2 - Summary progress output (use with Jupyter if you want to know the loss at each epoch)

__Predictions from our previous neural network__

Result from a neural network is an array. To see the dimension of this array we can use 'our array name'.shape.

In [24]:
pred = model.predict(x)
print(f"Shape: {pred.shape}") # printing the shape
print(pred[0:10])

Shape: (398, 1)
[[ 7.601251 ]
 [ 4.6441894]
 [ 5.885797 ]
 [ 8.292047 ]
 [ 7.9046874]
 [ 0.8491453]
 [-2.0485291]
 [-0.7053591]
 [-0.9067141]
 [ 0.6704649]]


We want to test if the predictions are good or bad. The correct MPG for each car is on the data.
First we calculate the Means Square Error.

In [25]:
# Mean square error

score = np.sqrt(metrics.mean_squared_error(pred,y))
print(score)

8.16664740689623


__Printing data against the prediction for the 10 first cars__

In [26]:
for i in range(10):
    print(f"MPG: {y[i]}" + f" Predicted MPG: {pred[i]}")

MPG: 18.0 Predicted MPG: [7.601251]
MPG: 15.0 Predicted MPG: [4.6441894]
MPG: 18.0 Predicted MPG: [5.885797]
MPG: 16.0 Predicted MPG: [8.292047]
MPG: 17.0 Predicted MPG: [7.9046874]
MPG: 15.0 Predicted MPG: [0.8491453]
MPG: 14.0 Predicted MPG: [-2.0485291]
MPG: 14.0 Predicted MPG: [-0.7053591]
MPG: 14.0 Predicted MPG: [-0.9067141]
MPG: 15.0 Predicted MPG: [0.6704649]


## Simple classification of the Iris data set.

Classification: a neural network tries to classify into one or more classes a data set. 
To evaluate classification networks we study the percentage of items that where classified
incorrectly.

This is like gradding a multiple answer exam. In this case the output is a classification with a 
percent giving us a measure of the quality of this classification.


Example: exam classification neural network

We have a multianswer question with possible answer a,b,c,d. The trained neural network tell us that
we have A: 0.1, B: 0.8, C: 0.05, D: 0.05.


__Example: data set iris__

We predict the species from some data about the flower as sepal longitud, sepal width, petal longitud, petal width.

In [30]:
import pandas as pd
import io
import requests
import numpy as np
from sklearn import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping

# loading the data from Heaton's website

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/iris.csv", 
    na_values=['NA', '?'])

# Getting a matrix from a data frame

x = df[['sepal_l','sepal_w', 'petal_l', 'petal_w']].values
dummies = pd.get_dummies(df['species']) # Convert categorical variable into dummy/indicator variables.
                                        # Classification
species = dummies.columns # this creates a variable which gives you back the species from the dummy label
y = dummies.values # this creates an array with 0,1,2 indicating the species

# Build neural network
model = Sequential()
model.add(Dense(50, input_dim=x.shape[1], activation='relu')) # Hidden 1, 50 neurons - layer 2
model.add(Dense(25, activation='relu')) # Hidden 2, 25 neurons, layer 3
model.add(Dense(y.shape[1],activation='softmax')) # Output, 1 output neuron, layer 4

model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

Epoch 1/100
5/5 - 0s - loss: 1.2110
Epoch 2/100
5/5 - 0s - loss: 1.0681
Epoch 3/100
5/5 - 0s - loss: 0.9664
Epoch 4/100
5/5 - 0s - loss: 0.8977
Epoch 5/100
5/5 - 0s - loss: 0.8540
Epoch 6/100
5/5 - 0s - loss: 0.8092
Epoch 7/100
5/5 - 0s - loss: 0.7587
Epoch 8/100
5/5 - 0s - loss: 0.7137
Epoch 9/100
5/5 - 0s - loss: 0.6717
Epoch 10/100
5/5 - 0s - loss: 0.6353
Epoch 11/100
5/5 - 0s - loss: 0.6017
Epoch 12/100
5/5 - 0s - loss: 0.5691
Epoch 13/100
5/5 - 0s - loss: 0.5384
Epoch 14/100
5/5 - 0s - loss: 0.5128
Epoch 15/100
5/5 - 0s - loss: 0.4844
Epoch 16/100
5/5 - 0s - loss: 0.4566
Epoch 17/100
5/5 - 0s - loss: 0.4341
Epoch 18/100
5/5 - 0s - loss: 0.4242
Epoch 19/100
5/5 - 0s - loss: 0.4078
Epoch 20/100
5/5 - 0s - loss: 0.3887
Epoch 21/100
5/5 - 0s - loss: 0.3743
Epoch 22/100
5/5 - 0s - loss: 0.3601
Epoch 23/100
5/5 - 0s - loss: 0.3483
Epoch 24/100
5/5 - 0s - loss: 0.3374
Epoch 25/100
5/5 - 0s - loss: 0.3247
Epoch 26/100
5/5 - 0s - loss: 0.3133
Epoch 27/100
5/5 - 0s - loss: 0.3024
Epoch 28/1

In [31]:
# Predictions using our neural network (first 10 values)

pred = model.predict(x)
print(f"Shape: {pred.shape}")
print(pred[0:10])

Shape: (150, 3)
[[9.9770373e-01 2.2961216e-03 6.7637941e-08]
 [9.9509549e-01 4.9043368e-03 2.8796302e-07]
 [9.9630773e-01 3.6920840e-03 2.3031738e-07]
 [9.9385637e-01 6.1429772e-03 6.0425356e-07]
 [9.9787009e-01 2.1297478e-03 6.8409584e-08]
 [9.9749678e-01 2.5030603e-03 7.0227543e-08]
 [9.9632877e-01 3.6708296e-03 3.1330754e-07]
 [9.9699318e-01 3.0067430e-03 1.2441055e-07]
 [9.9234349e-01 7.6554483e-03 1.0754263e-06]
 [9.9571347e-01 4.2862999e-03 2.1523297e-07]]


In [32]:
np.set_printoptions(suppress=True) # deactivating scientific notation
print(pred[0:10])

[[0.99770373 0.00229612 0.00000007]
 [0.9950955  0.00490434 0.00000029]
 [0.99630773 0.00369208 0.00000023]
 [0.9938564  0.00614298 0.0000006 ]
 [0.9978701  0.00212975 0.00000007]
 [0.9974968  0.00250306 0.00000007]
 [0.9963288  0.00367083 0.00000031]
 [0.9969932  0.00300674 0.00000012]
 [0.9923435  0.00765545 0.00000108]
 [0.9957135  0.0042863  0.00000022]]


In [33]:
# Real values

print(y[0:10])

np.argmax(pred, axis=1)

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In general, the program considers the column with highest prediction to be the prediction of the neural network.
The argmax function finds the index of the maximum prediction for each row.

In [34]:
predict_classes = np.argmax(pred,axis=1) # np.argmax returns the indices of the maximum values along an axis.
expected_classes = np.argmax(y,axis=1)
print(f"Predictions: {predict_classes}")
print(f"Expected: {expected_classes}")

Predictions: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Expected: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [35]:
# Turning this back into species

print(species[predict_classes[1:10]])

Index(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'],
      dtype='object')


In [36]:
# Testing the result. For all of the iris predictions, what percent were correct?
#
# We want to study accuracy. -> accuracy does not consider how confident the neural network was in each prediction.
# Accuracy is a global measure

from sklearn.metrics import accuracy_score

correct = accuracy_score(expected_classes,predict_classes)
print(f"Accuracy: {correct}")

Accuracy: 0.9866666666666667


In [37]:
df

sepal_l  sepal_w  petal_l  petal_w         species
0        5.1      3.5      1.4      0.2     Iris-setosa
1        4.9      3.0      1.4      0.2     Iris-setosa
2        4.7      3.2      1.3      0.2     Iris-setosa
3        4.6      3.1      1.5      0.2     Iris-setosa
4        5.0      3.6      1.4      0.2     Iris-setosa
..       ...      ...      ...      ...             ...
145      6.7      3.0      5.2      2.3  Iris-virginica
146      6.3      2.5      5.0      1.9  Iris-virginica
147      6.5      3.0      5.2      2.0  Iris-virginica
148      6.2      3.4      5.4      2.3  Iris-virginica
149      5.9      3.0      5.1      1.8  Iris-virginica

[150 rows x 5 columns]

In [38]:
## Some particular predictions for the arrays [5.0,3.0,4.0,2.0] and [5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8].
## Here we use our neural network.

sample_flower = np.array( [[5.0,3.0,4.0,2.0]], dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred)
print(f"Predict that {sample_flower} is: {species[pred]}")

[[0.00024656 0.11699673 0.88275665]]
Predict that [[5. 3. 4. 2.]] is: Iris-virginica


In [39]:
sample_flower = np.array( [[5.0,3.0,4.0,2.0],[5.2,3.5,1.5,0.8]],\
        dtype=float)
pred = model.predict(sample_flower)
print(pred)
pred = np.argmax(pred,axis=1)
print(f"Predict that these two flowers {sample_flower} ")
print(f"are: {species[pred]}")

[[0.00024656 0.11699675 0.88275665]
 [0.9895929  0.0104061  0.00000098]]
Predict that these two flowers [[5.  3.  4.  2. ]
 [5.2 3.5 1.5 0.8]] 
are: Index(['Iris-virginica', 'Iris-setosa'], dtype='object')


# Saving and Loading Keral Neural Networks


We expend resources (time, computation time, money, etc) when training neural network. It is a good idea
to save this neural networks so that they can be reloaded. (We save the weights).

Keras provides 3 formas: YAML, JSON, HDF5.

We will use HDF5.

__Example:__ We use againg the GTM Neural Network

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import pandas as pd
import io
import os
import requests
import numpy as np
from sklearn import metrics

save_path = "." # we save the neural network in the same folder

# Loading the data set from Heaton's website.

df = pd.read_csv(
    "https://data.heatonresearch.com/data/t81-558/auto-mpg.csv", 
    na_values=['NA', '?'])

cars = df['name']

# Filling the empty values


df['horsepower'] = df['horsepower'].fillna(df['horsepower'].median())

# Obtaining a matrix from a data set 

x = df[['cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'year', 'origin']].values # this is the predictor
y = df['mpg'].values # regression --> this is the dependent variable

# Build the neural network -> 4 layers, inputs, hidden layer, hidden layer, output
model = Sequential()
model.add(Dense(25, input_dim=x.shape[1], activation='relu')) # Hidden 1, 25 neurons after the inputs
model.add(Dense(10, activation='relu')) # Hidden 2, 10 neurons 
model.add(Dense(1)) # Output, 1 neuron for the output
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x,y,verbose=2,epochs=100)

# Predict
pred = model.predict(x)

# Mean Square Error
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"Before save score (RMSE): {score}")

# Some remarks about saving a neural network.

# When we train a neural network we are minimizing the error for the weights w
# This happens to be equivalent to some Generalized linear model where you 
# try to fit some data set using a particular model which uses weights.
# One example of these models is logistic regression, where given a matrix
# X containing the data set you want to find the probability for a certain
# row for belonging to certain group or category. 


# save neural network structure to JSON (no weights)
model_json = model.to_json() # this is the code for saving the neuron
with open(os.path.join(save_path,"network.json"), "w") as json_file:
    json_file.write(model_json)

# save neural network structure to YAML (no weights)
model_yaml = model.to_yaml()
with open(os.path.join(save_path,"network.yaml"), "w") as yaml_file:
    yaml_file.write(model_yaml)

# save entire network to HDF5 (save everything, suggested)
model.save(os.path.join(save_path,"network.h5"))

Epoch 1/100
13/13 - 0s - loss: 247210.0938
Epoch 2/100
13/13 - 0s - loss: 17899.0410
Epoch 3/100
13/13 - 0s - loss: 5742.4458
Epoch 4/100
13/13 - 0s - loss: 3059.1477
Epoch 5/100
13/13 - 0s - loss: 332.0005
Epoch 6/100
13/13 - 0s - loss: 388.3457
Epoch 7/100
13/13 - 0s - loss: 168.9377
Epoch 8/100
13/13 - 0s - loss: 184.0500
Epoch 9/100
13/13 - 0s - loss: 162.7780
Epoch 10/100
13/13 - 0s - loss: 159.0713
Epoch 11/100
13/13 - 0s - loss: 156.1283
Epoch 12/100
13/13 - 0s - loss: 153.2866
Epoch 13/100
13/13 - 0s - loss: 151.0939
Epoch 14/100
13/13 - 0s - loss: 147.4653
Epoch 15/100
13/13 - 0s - loss: 145.5288
Epoch 16/100
13/13 - 0s - loss: 141.9004
Epoch 17/100
13/13 - 0s - loss: 138.8959
Epoch 18/100
13/13 - 0s - loss: 136.0509
Epoch 19/100
13/13 - 0s - loss: 133.4520
Epoch 20/100
13/13 - 0s - loss: 130.8322
Epoch 21/100
13/13 - 0s - loss: 128.0443
Epoch 22/100
13/13 - 0s - loss: 126.1390
Epoch 23/100
13/13 - 0s - loss: 123.0789
Epoch 24/100
13/13 - 0s - loss: 121.1961
Epoch 25/100
13/13

In [5]:
x.shape

(398, 7)

# Reloading a neural network.

In [43]:
from tensorflow.keras.models import load_model
model2 = load_model(os.path.join(save_path,"network.h5"))
pred = model2.predict(x)
# Measure RMSE error.  RMSE is common for regression.
score = np.sqrt(metrics.mean_squared_error(pred,y))
print(f"After load score (RMSE): {score}")

# Both have the same RMSE - Root Square Mean Error.

After load score (RMSE): 7.308954587399029
